import type { Conversation } from '../features/conversations/types'
import type { ThemePreference } from '../lib/theme'
import { ThemeControl } from './ThemeControl'

interface Props { conversations: Conversation[]; activeId?: string; onNew: () => void; onOpen: (id: string) => void; onDelete: (id: string) => void; collapsed: boolean; onToggle: () => void; themePreference: ThemePreference; onThemeChange: (value: ThemePreference) => void }
const day = 86_400_000
function groupFor(value: string) { const days = Math.floor((new Date().setHours(0, 0, 0, 0) - new Date(value).setHours(0, 0, 0, 0)) / day); return days === 0 ? 'Today' : days === 1 ? 'Yesterday' : days < 7 ? 'Previous 7 Days' : 'Older' }
const groups = ['Today', 'Yesterday', 'Previous 7 Days', 'Older']
export function ConversationSidebar({ conversations, activeId, onNew, onOpen, onDelete, collapsed, onToggle, themePreference, onThemeChange }: Props) { const visible = conversations.filter((item) => !(item.id === activeId && item.messages.some((message) => message.status === 'streaming'))); return <aside className={`conversation-sidebar ${collapsed ? 'collapsed' : ''}`} aria-label="Search history"><div className="sidebar-top"><button className="sidebar-toggle" aria-label="Toggle search history" onClick={onToggle}>☰</button>{!collapsed && <span className="sidebar-brand">AI Search</span>}</div><button className="sidebar-new" aria-label="New search" onClick={onNew}><span aria-hidden="true">{collapsed ? '+' : 'New search'}</span></button>{!collapsed && <div className="history-list">{visible.length === 0 && <p className="history-empty">Your searches will appear here.</p>}{groups.map((group) => { const items = visible.filter((item) => groupFor(item.updatedAt) === group); return items.length ? <section key={group}><h2>{group}</h2>{items.map((item) => <div className={`history-item ${item.id === activeId ? 'active' : ''}`} key={item.id}><button onClick={() => onOpen(item.id)} aria-current={item.id === activeId ? 'page' : undefined}>{item.title}</button><button className="history-delete" aria-label={`Delete ${item.title}`} onClick={() => { if (confirm(`Delete “${item.title}”?`)) onDelete(item.id) }}>×</button></div>)}</section> : null })}</div>}<footer className="sidebar-footer"><ThemeControl preference={themePreference} onChange={onThemeChange} /></footer></aside> }
